spring.application.name=football
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

sentry.dsn=https://1d8975da90afb4493b86adc83fb4b214@o4511268146839552.ingest.us.sentry.io/4511268184719360
sentry.send-default-pii=true
